name: ci test

on:
  push:
    branches:
      - 'main'

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
      -
        name: Build and push
        uses: docker/bake-action@v4
        with:
          context: DockerFileFolder/   or .
          push: true
          tags: vinaykumar75/vinay:latest
